-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Client"
(
    phone_num integer NOT NULL,
    name character varying NOT NULL,
    client_id integer NOT NULL,
    manager_id integer,
    PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS public."Table"
(
    "number" integer NOT NULL,
    num_of_seats integer NOT NULL,
    section character varying NOT NULL,
    table_id integer NOT NULL,
    PRIMARY KEY (table_id)
);

CREATE TABLE IF NOT EXISTS public."Manager"
(
    email text NOT NULL,
    shift integer NOT NULL,
    "position" character varying NOT NULL,
    manager_id integer NOT NULL,
    PRIMARY KEY (manager_id)
);

CREATE TABLE IF NOT EXISTS public."Client_Table"
(
    "Client_client_id" integer NOT NULL,
    "Table_table_id" integer NOT NULL,
    date date NOT NULL,
    CONSTRAINT client_table_pk PRIMARY KEY ("Client_client_id", "Table_table_id", date)
);

ALTER TABLE IF EXISTS public."Client"
    ADD FOREIGN KEY (manager_id)
    REFERENCES public."Manager" (manager_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Client_Table"
    ADD FOREIGN KEY ("Client_client_id")
    REFERENCES public."Client" (client_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Client_Table"
    ADD FOREIGN KEY ("Table_table_id")
    REFERENCES public."Table" (table_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;